#!/usr/bin/env bash

# Run this script with a file as input, and it's sha512sum will added
# to your xorg clipboard.
#
# Requires: xclip, sha512sum

[[ ! -f "$1" ]] && exit 1

echo -n $(sha512sum "$1" | sed 's|\ [^\ ]*$||') | xclip -sel clip
